spring.application.name=auth-system

spring.datasource.url = jdbc:mysql://localhost:3306/auth_db
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

spring.datasource.username = root
spring.datasource.password = vinay@123

jwt.secret = 6b4f2a9d1e8c3b7a5f0d2e9c4b6a1f3d8e5c2b7a4f1d6e3c0b9a2f5d8e1c4b7a

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect